// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrtDxU4pfEEN4t8gPG77eIkdtctaJYOw',
    appId: '1:1042387473888:web:0cbbb2ee618c07388e4785',
    messagingSenderId: '1042387473888',
    projectId: 'fruits-hub-c571a',
    authDomain: 'fruits-hub-c571a.firebaseapp.com',
    storageBucket: 'fruits-hub-c571a.appspot.com',
    measurementId: 'G-JJW44EMZ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsShusLQ0hap-lhIhkXZ0ZFsey9p5PKlo',
    appId: '1:1042387473888:android:fec43fe53b6035758e4785',
    messagingSenderId: '1042387473888',
    projectId: 'fruits-hub-c571a',
    storageBucket: 'fruits-hub-c571a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuaBB1A_wnLnEU9LcY3ATPsWpzlO9_Hys',
    appId: '1:1042387473888:ios:54ff8df32c1129958e4785',
    messagingSenderId: '1042387473888',
    projectId: 'fruits-hub-c571a',
    storageBucket: 'fruits-hub-c571a.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuaBB1A_wnLnEU9LcY3ATPsWpzlO9_Hys',
    appId: '1:1042387473888:ios:54ff8df32c1129958e4785',
    messagingSenderId: '1042387473888',
    projectId: 'fruits-hub-c571a',
    storageBucket: 'fruits-hub-c571a.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrtDxU4pfEEN4t8gPG77eIkdtctaJYOw',
    appId: '1:1042387473888:web:a6054ed03aaec7c98e4785',
    messagingSenderId: '1042387473888',
    projectId: 'fruits-hub-c571a',
    authDomain: 'fruits-hub-c571a.firebaseapp.com',
    storageBucket: 'fruits-hub-c571a.appspot.com',
    measurementId: 'G-3FX7K6SD8H',
  );

}